### ISSUE TITLE
Add a mentor's name to each work item

### ISSUE THREAD

**Issue by cathyhongzhang** [cncf/clotributor#52] opened 2022-12-01 19:42 UTC
It will be great to add a mentor's name to each work item so that the new contributor knows whom to ask for guidance/help.

**Comment by tegioz** [comment] 2022-12-02 07:35
Related to #50

**Comment by tegioz** [comment] 2023-05-26 08:37
Thanks @cathyhongzhang!

CLOTributor feeds mostly from information available in the issues (plus some details from the repository). To make something like this work, the mentor name should be part of the issue somehow (maybe as a label?).

At the moment the main CLOTributor's goal is to make it easier to discover and find issues available across CNCF (and other foundations) projects for contributors. But once a contributor finds an interesting issue that suits them, the process continues in GitHub and, once the issue is assigned, CLOTributor stops listing it. So hopefully contributors will find the guidance and help they need on the issue, which has all the work's context and it's probably where all conversations will happen.

But it's possible that eventually CLOTributor will take more responsibilities and in that case we'd definitely need to track both mentors and mentees.

Will close this one for now, please feel free to reopen if needed 🙂

**Closed by tegioz** 2023-05-26 08:37 UTC
